name: Build Example App

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        channel: 'stable'
    - run: flutter pub get
    - run: flutter build apk --debug --verbose
    - uses: actions/upload-artifact@v1
      with:
        name: example-apk-debug
        path: build/app/outputs/flutter-apk/app-debug.apk
